{{- if .Values.secretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firehose.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": "keep"
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretConfig -}}
    {{- (print $key ": " ($val | toString | b64enc | quote )) | nindent 2 -}}
  {{- end }}
{{- end }}