apiVersion: v2
name: entropy
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: 0.1.0
dependencies:
- name: app
  version: "0.3.4"
  repository: "https://raystack.github.io/charts/"
