app:
  image:
    repository: gotocompany/entropy
    pullPolicy: Always
    tag: "latest"
  container:
    command:
      - entropy
    args:
      - serve
      - "--worker"
    livenessProbe:
      httpGet:
        path: /ping
        port: tcp
    readinessProbe:
      httpGet:
        path: /ping
        port: tcp
  podLabels: {}
  serviceAccountName: ""

  migration:
    enabled: true
    command:
      - entropy
    args:
      - migrate

  service:
    annotations: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: contour
    hosts:
      - host: entropy.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                port:
                  number: 80

  config:
    SERVER_PORT: 8080
    # SERVICE_HOST: 0.0.0.0
    # LOG_LEVEL: info
    # NEW_RELIC_ENABLED: false
    # NEW_RELIC_APP_NAME: entropy

  secretConfig: {}
