apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "meteor.name" . }}"
  namespace: {{ include "meteor.namespace" . }}
  labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 12 }}
{{- end }}
        spec:
          containers:
          - name: "{{ include "meteor.name" . }}"
            image: "{{ required `image.repository is required` .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - meteor
              - run
              - /opt/recipes
            volumeMounts:
              - name: "{{ include "meteor.name" . }}-volume"
                mountPath: /opt/recipes
              {{- range $k, $v := .Values.ssl_secrets }}
              - name: {{ $v }}
                mountPath: {{ printf "%s/%s" "/etc/secret" $v }}
              {{- end }}
            envFrom:
              - configMapRef:
                  name: "{{ include "meteor.name" . }}-variables-configmap"
            {{- if .Values.secretConfig }}
              - secretRef:
                  name: "{{ include "meteor.name" . }}-secret"
            {{- end }}
          restartPolicy: Never
          volumes:
            - name: "{{ include "meteor.name" . }}-volume"
              configMap:
                name: "{{ include "meteor.name" . }}-recipe-configmap"
                items:
                {{- range $k, $v := .Values.recipes }}
                - key: {{ $k }}
                  path: {{ $k }}
                {{- end }}
            {{- range $k, $v := .Values.ssl_secrets }}
            - name: {{ $v }}
              secret:
                defaultMode: 420
                optional: true
                secretName: {{ $v }}
            {{- end }}
          {{- if .Values.telegraf.enabled }}
          - name: telegraf-sidecar
            image: {{ .Values.telegraf.image }}
            args:
              {{- range .Values.telegraf.args }}
              - {{ . }}
              {{- end }}
            command:
              {{- range .Values.telegraf.command }}
              - {{ . }}
              {{- end }}
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: {{ .Values.telegraf.containerPort }}
                name: http
                protocol: {{ .Values.telegraf.protocol }}
            volumeMounts:
              - name: telegraf-conf
                mountPath: /etc/telegraf/
          {{- end }}
          volumes:
            {{- if .Values.telegraf.enabled }}
            - name: telegraf-conf
              configMap:
                name: {{ include "meteor.name" . }}-telegraf
            {{- end }}
