{{- if .Values.secretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "meteor.name" . }}-secret"
  namespace: {{ include "meteor.namespace" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretConfig -}}
    {{- (print $key ": " ($val | toString | b64enc | quote )) | nindent 2 -}}
  {{- end }}
{{- end }}