apiVersion: v1
description: Siren Helm chart
name: siren
version: 0.1.1
appVersion: v0.0.1
home: https://github.com/odpf/siren
sources:
- https://github.com/odpf/siren
- https://github.com/odpf/charts
