apiVersion: v2
name: siren
description: Siren Helm chart
version: 0.1.1
appVersion: v0.5.0
home: https://github.com/odpf/siren
dependencies:
- name: app
  version: "0.4.2"
  repository: "https://odpf.github.io/charts/"
  alias: app
  condition: app.enabled
- name: app
  version: "0.4.2"
  repository: "https://odpf.github.io/charts/"
  alias: notification-worker
  condition: notification-worker.enabled
- name: app
  version: "0.4.2"
  repository: "https://odpf.github.io/charts/"
  alias: notification-dlq-worker
  condition: notification-dlq-worker.enabled
