apiVersion: v2
name: siren
description: Siren Helm chart
version: 0.1.0
appVersion: v0.5.0
home: https://github.com/odpf/siren
dependencies:
- name: app
  version: "0.4.2"
  repository: "https://odpf.github.io/charts/"
  alias: siren-app
  condition: siren-app.enabled
- name: app
  version: "0.4.2"
  repository: "https://odpf.github.io/charts/"
  alias: siren-notification-worker
  condition: siren-notification-worker.enabled
- name: app
  version: "0.4.2"
  repository: "https://odpf.github.io/charts/"
  alias: siren-notification-dlq-worker
  condition: siren-notification-dlq-worker.enabled
