apiVersion: v2
name: dex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: app
  version: "0.4.0"
  repository: "https://odpf.github.io/charts/"
