apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "application.name" . }}-configmap"
  namespace: {{ include "application.namespace" . }}
data:
{{- range $k, $v := .Values.config }}
{{ $k | indent 2 }}: |-
{{ $v | indent 4 }}
{{- end }}
