apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "application.name" . }}"
  namespace: {{ .Values.namespace }}
  labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 12 }}
{{- end }}
        spec:
          containers:
            - name: "{{ include "application.name" . }}"
              image: "{{ required `image.repository is required` .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
              {{- range .Values.cron.entryPoint }}
                - {{ . }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: "{{ include "application.name" . }}-configmap"
                - secretRef:
                    name: "{{ include "application.name" . }}-secret"
          restartPolicy: Never
