{{- if .Values.secretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretConfig -}}
    {{- (print $key ": " ($val | toString | b64enc | quote )) | nindent 2 -}}
  {{- end }}
{{- end }}
