apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app.fullname" . }}"
  namespace: "{{ include "app.namespace" . }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": "keep"
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}