apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app.fullname" . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}