{{- if .Values.cron.enabled }}
{{- $fullName := include "app.fullname" . -}}
{{- $appLabels := include "app.labels" . -}}
{{- $appSelectorLabels := include "app.selectorLabels" . -}}
{{- range $i, $job := .Values.cron.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%d-%s" $.Release.Namespace $i $job.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $appLabels | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
        {{- $appSelectorLabels | nindent 12 }}
        spec:
          containers:
            - name: {{ $job.name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
              {{- toYaml $job.command | nindent 16 }}
              args:
              {{- toYaml $job.args | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: {{ $fullName }}
                - secretRef:
                    name: {{ $fullName }}-secret
          restartPolicy: {{ $job.restartPolicy }}
---
{{- end -}}
{{- end -}}