{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.rbac.annotations }}
    {{- .Values.rbac.annotations | toYaml | nindent 4 }}
    {{- end }}
rules:
  {{- if .Values.rbac.rules }}
  {{- .Values.rbac.rules | toYaml | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.fullname" . }}
    namespace: "{{ include "app.namespace" . }}"
{{- end }}
